//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Management.PHP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Management.PHP.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add PHP Setting.
        /// </summary>
        internal static string AddEditSettingDialogAddSetting {
            get {
                return ResourceManager.GetString("AddEditSettingDialogAddSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit PHP Setting.
        /// </summary>
        internal static string AddEditSettingDialogEditSetting {
            get {
                return ResourceManager.GetString("AddEditSettingDialogEditSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about this setting.
        /// </summary>
        internal static string AddEditSettingDialogLearnMore {
            get {
                return ResourceManager.GetString("AddEditSettingDialogLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string AddEditSettingDialogName {
            get {
                return ResourceManager.GetString("AddEditSettingDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section:.
        /// </summary>
        internal static string AddEditSettingDialogSection {
            get {
                return ResourceManager.GetString("AddEditSettingDialogSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        internal static string AddEditSettingDialogValue {
            get {
                return ResourceManager.GetString("AddEditSettingDialogValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an extension.
        /// </summary>
        internal static string AddExtensionDialogAddExtension {
            get {
                return ResourceManager.GetString("AddExtensionDialogAddExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: C:\Temp\php_wincache.dll.
        /// </summary>
        internal static string AddExtensionDialogExample {
            get {
                return ResourceManager.GetString("AddExtensionDialogExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP extension (php*.dll)|php*.dll|All files (*.*)|*.*.
        /// </summary>
        internal static string AddExtensionDialogOpenFileFilter {
            get {
                return ResourceManager.GetString("AddExtensionDialogOpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select extension binary file.
        /// </summary>
        internal static string AddExtensionDialogOpenFileTitle {
            get {
                return ResourceManager.GetString("AddExtensionDialogOpenFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a path to extension&apos;s binary file:.
        /// </summary>
        internal static string AddExtensionDialogProvidePath {
            get {
                return ResourceManager.GetString("AddExtensionDialogProvidePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable PHP extensions and configure PHP extensions settings..
        /// </summary>
        internal static string AllExtensionsPageDescription {
            get {
                return ResourceManager.GetString("AllExtensionsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string AllExtensionsPageDisabledGroup {
            get {
                return ResourceManager.GetString("AllExtensionsPageDisabledGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string AllExtensionsPageDisableTask {
            get {
                return ResourceManager.GetString("AllExtensionsPageDisableTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string AllExtensionsPageEnabledGroup {
            get {
                return ResourceManager.GetString("AllExtensionsPageEnabledGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string AllExtensionsPageEnableTask {
            get {
                return ResourceManager.GetString("AllExtensionsPageEnableTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting extensions.
        /// </summary>
        internal static string AllExtensionsPageGettingExtensions {
            get {
                return ResourceManager.GetString("AllExtensionsPageGettingExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP extensions provide additional functionality to PHP runtime, such as database connectivity, caching, debugging and others. Use this feature to enable or disable PHP extensions and to configure PHP extensions settings..
        /// </summary>
        internal static string AllExtensionsPageLongDescription {
            get {
                return ResourceManager.GetString("AllExtensionsPageLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string AllExtensionsPageNameField {
            get {
                return ResourceManager.GetString("AllExtensionsPageNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string AllExtensionsPageStateField {
            get {
                return ResourceManager.GetString("AllExtensionsPageStateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Extensions.
        /// </summary>
        internal static string AllExtensionsPageTitle {
            get {
                return ResourceManager.GetString("AllExtensionsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        internal static string AllPagesAddTask {
            get {
                return ResourceManager.GetString("AllPagesAddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to main page.
        /// </summary>
        internal static string AllPagesGoBackTask {
            get {
                return ResourceManager.GetString("AllPagesGoBackTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open php.ini.
        /// </summary>
        internal static string AllPagesOpenPHPIniTask {
            get {
                return ResourceManager.GetString("AllPagesOpenPHPIniTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These settings are read-only. They can only be changed by a server administrator..
        /// </summary>
        internal static string AllPagesPageIsReadOnly {
            get {
                return ResourceManager.GetString("AllPagesPageIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure all php settings.
        /// </summary>
        internal static string AllSettingsPageDescription {
            get {
                return ResourceManager.GetString("AllSettingsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit....
        /// </summary>
        internal static string AllSettingsPageEditTask {
            get {
                return ResourceManager.GetString("AllSettingsPageEditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting settings.
        /// </summary>
        internal static string AllSettingsPageGettingSettings {
            get {
                return ResourceManager.GetString("AllSettingsPageGettingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure all php settings that are stored in php.ini file. These setting control all aspects of PHP runtime, such error reporting, security, sessions and others..
        /// </summary>
        internal static string AllSettingsPageLongDescription {
            get {
                return ResourceManager.GetString("AllSettingsPageLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string AllSettingsPageNameField {
            get {
                return ResourceManager.GetString("AllSettingsPageNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string AllSettingsPageRemoveTask {
            get {
                return ResourceManager.GetString("AllSettingsPageRemoveTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string AllSettingsPageSectionField {
            get {
                return ResourceManager.GetString("AllSettingsPageSectionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Settings.
        /// </summary>
        internal static string AllSettingsPageTitle {
            get {
                return ResourceManager.GetString("AllSettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string AllSettingsPageValueField {
            get {
                return ResourceManager.GetString("AllSettingsPageValueField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select PHP version:.
        /// </summary>
        internal static string ChangeVersionDialogSelectVersion {
            get {
                return ResourceManager.GetString("ChangeVersionDialogSelectVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PHP version.
        /// </summary>
        internal static string ChangeVersionDialogTitle {
            get {
                return ResourceManager.GetString("ChangeVersionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHP directive &quot;cgi.force_redirect&quot; is not set to &quot;0&quot;..
        /// </summary>
        internal static string ConfigIssueCgiForceRedirectNotCorrect {
            get {
                return ResourceManager.GetString("ConfigIssueCgiForceRedirectNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHP directive &quot;cgi.force_redirect&quot; is not set..
        /// </summary>
        internal static string ConfigIssueCgiForceRedirectNotSet {
            get {
                return ResourceManager.GetString("ConfigIssueCgiForceRedirectNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is recommended to turn &quot;cgi.force_redirect&quot; off when PHP is run on IIS..
        /// </summary>
        internal static string ConfigIssueCgiForceRedirectRecommend {
            get {
                return ResourceManager.GetString("ConfigIssueCgiForceRedirectRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHP directive &quot;cgi.fix_pathinfo&quot; is not set to &quot;1&quot;..
        /// </summary>
        internal static string ConfigIssueCgiPathInfoNotCorrect {
            get {
                return ResourceManager.GetString("ConfigIssueCgiPathInfoNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHP directive &quot;cgi.fix_pathinfo&quot; is not set..
        /// </summary>
        internal static string ConfigIssueCgiPathInfoNotSet {
            get {
                return ResourceManager.GetString("ConfigIssueCgiPathInfoNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting provides real PATH_INFO/ PATH_TRANSLATED support for CGI and FastCGI. It is recommended to enable this support by setting it to &quot;1&quot;..
        /// </summary>
        internal static string ConfigIssueCgiPathInfoRecommend {
            get {
                return ResourceManager.GetString("ConfigIssueCgiPathInfoRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHP directive date.timezone is not set..
        /// </summary>
        internal static string ConfigIssueDateTimeZoneNotSet {
            get {
                return ResourceManager.GetString("ConfigIssueDateTimeZoneNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not safe to rely on the system&apos;s timezone settings. It is recommended to explicitly set the timezone information by using date.timezone directive or the date_default_timezone_set() function..
        /// </summary>
        internal static string ConfigIssueDateTimeZoneRecommend {
            get {
                return ResourceManager.GetString("ConfigIssueDateTimeZoneRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index.php is not the first in the list of IIS default documents..
        /// </summary>
        internal static string ConfigIssueDefaultDocumentNotFirst {
            get {
                return ResourceManager.GetString("ConfigIssueDefaultDocumentNotFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index.php is not set as a default document..
        /// </summary>
        internal static string ConfigIssueDefaultDocumentNotSet {
            get {
                return ResourceManager.GetString("ConfigIssueDefaultDocumentNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Majority of PHP applications use index.php as the default file name for web requests. It is recommended to add index.php to the list of default documents in IIS and ensure that it is the first in the list..
        /// </summary>
        internal static string ConfigIssueDefaultDocumentRecommend {
            get {
                return ResourceManager.GetString("ConfigIssueDefaultDocumentRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHP directive &quot;error_log&quot; is using a non-existent directory..
        /// </summary>
        internal static string ConfigIssueErrorLogNotCorrect {
            get {
                return ResourceManager.GetString("ConfigIssueErrorLogNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHP directive &quot;error_log&quot; is not set..
        /// </summary>
        internal static string ConfigIssueErrorLogNotSet {
            get {
                return ResourceManager.GetString("ConfigIssueErrorLogNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;error_log&quot; specifies the name of the file where script errors should be logged to. It is recommended to set this to an absolute file path and the file should be writable by the web server..
        /// </summary>
        internal static string ConfigIssueErrorLogRecommend {
            get {
                return ResourceManager.GetString("ConfigIssueErrorLogRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHP directive &quot;extension_dir&quot; does not contain an absolute file path..
        /// </summary>
        internal static string ConfigIssueExtensionDirIncorrect {
            get {
                return ResourceManager.GetString("ConfigIssueExtensionDirIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHP directive &quot;extension_dir&quot; is not set..
        /// </summary>
        internal static string ConfigIssueExtensionDirNotSet {
            get {
                return ResourceManager.GetString("ConfigIssueExtensionDirNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;extension_dir&quot; is used to specify a directory path in which PHP should look for dynamically loadable extensions. It is recommended to use absolute directory path for this setting..
        /// </summary>
        internal static string ConfigIssueExtensionDirRecommend {
            get {
                return ResourceManager.GetString("ConfigIssueExtensionDirRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHP directive &quot;fastcgi.impersonate&quot; is not set to &quot;1&quot;..
        /// </summary>
        internal static string ConfigIssueFastCgiImpersonateNotCorrect {
            get {
                return ResourceManager.GetString("ConfigIssueFastCgiImpersonateNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHP directive &quot;fastcgi.impersonate&quot; is not set..
        /// </summary>
        internal static string ConfigIssueFastCgiImpersonateNotSet {
            get {
                return ResourceManager.GetString("ConfigIssueFastCgiImpersonateNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FastCGI supports the ability to impersonate security tokens of the calling client. This allows IIS to define the security context that the request runs under. It is recommended to enable impersonation by setting this directive to &quot;1&quot;..
        /// </summary>
        internal static string ConfigIssueFastCgiImpersonateRecommend {
            get {
                return ResourceManager.GetString("ConfigIssueFastCgiImpersonateRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHP directive &quot;log_errors&quot; is not set to &quot;On&quot;..
        /// </summary>
        internal static string ConfigIssueLogErrorsNotCorrect {
            get {
                return ResourceManager.GetString("ConfigIssueLogErrorsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHP directive &quot;log_errors&quot; is not set..
        /// </summary>
        internal static string ConfigIssueLogErrorsNotSet {
            get {
                return ResourceManager.GetString("ConfigIssueLogErrorsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;log_errors&quot; controls whether PHP logs errors and warning to a log file. It is recommended to set this to &quot;On&quot;..
        /// </summary>
        internal static string ConfigIssueLogErrorsRecommend {
            get {
                return ResourceManager.GetString("ConfigIssueLogErrorsRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FastCGI setting monitorChangesTo is pointing to a wrong file..
        /// </summary>
        internal static string ConfigIssueMonitorChangesIncorrect {
            get {
                return ResourceManager.GetString("ConfigIssueMonitorChangesIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FastCGI setting monitorChangesTo is not set..
        /// </summary>
        internal static string ConfigIssueMonitorChangesNotSet {
            get {
                return ResourceManager.GetString("ConfigIssueMonitorChangesNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The monitorChangesTo setting is used to configure FastCGI to monitor a file so that when file is changed the FastCGI processes are recycled. It is recommended to set this to point to php.ini file that is loaded by PHP. That way the configuration changes to PHP will take effect immediately after the php.ini is updated..
        /// </summary>
        internal static string ConfigIssueMonitorChangesRecommend {
            get {
                return ResourceManager.GetString("ConfigIssueMonitorChangesRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Not set&gt;.
        /// </summary>
        internal static string ConfigIssueNone {
            get {
                return ResourceManager.GetString("ConfigIssueNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for PHP_FCGI_MAX_REQUESTS is smaller than the value for FastCGI instanceMaxRequests setting..
        /// </summary>
        internal static string ConfigIssuePHPMaxRequestsIncorrect {
            get {
                return ResourceManager.GetString("ConfigIssuePHPMaxRequestsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The environment variable PHP_FCGI_MAX_REQUESTS is not set for PHP processes..
        /// </summary>
        internal static string ConfigIssuePHPMaxRequestsNotSet {
            get {
                return ResourceManager.GetString("ConfigIssuePHPMaxRequestsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHP_FCGI_MAX_REQUESTS environment variable is used to specify the number of requests that PHP executable will handle before it gets recycled. It is recommended that the value for this variable is greater or equal to the value for FastCgi instanceMaxRequests setting. That way the IIS FastCGI process recycling logic will not conflict with PHP recycling behavior..
        /// </summary>
        internal static string ConfigIssuePHPMaxRequestsRecommend {
            get {
                return ResourceManager.GetString("ConfigIssuePHPMaxRequestsRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHPRC environment variable points to a directory that does not contain php.ini file..
        /// </summary>
        internal static string ConfigIssuePHPRCFileNotExists {
            get {
                return ResourceManager.GetString("ConfigIssuePHPRCFileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHPRC environment variable is not set for PHP processes..
        /// </summary>
        internal static string ConfigIssuePHPRCNotSet {
            get {
                return ResourceManager.GetString("ConfigIssuePHPRCNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHPRC environment variable is used to specify the directory that contains a PHP configuration file php.ini. PHP will load that configuration file during startup. It is recommended to always set this environment variable per PHP registration, thus avoiding situations when PHP loads wrong configuration file..
        /// </summary>
        internal static string ConfigIssuePHPRCRecommend {
            get {
                return ResourceManager.GetString("ConfigIssuePHPRCRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resourceType attribute of an IIS handler for PHP is not set to &quot;Either&quot;..
        /// </summary>
        internal static string ConfigIssueResourceTypeIncorrect {
            get {
                return ResourceManager.GetString("ConfigIssueResourceTypeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IIS handler attribute resourceType is used to specify a condition when handler will be invoked for a web request. When configuring the handler for PHP, it is recommended to set this attribute to &quot;Either&quot; for security reasons. That way the handler will be invoked only if the requested URL maps to a file or a folder on the file system..
        /// </summary>
        internal static string ConfigIssueResourceTypeRecommend {
            get {
                return ResourceManager.GetString("ConfigIssueResourceTypeRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHP directive &quot;session.save_path&quot; uses a non-existent directory..
        /// </summary>
        internal static string ConfigIssueSessionPathNotCorrect {
            get {
                return ResourceManager.GetString("ConfigIssueSessionPathNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHP directive &quot;session.save_path&quot; is not set..
        /// </summary>
        internal static string ConfigIssueSessionPathNotSet {
            get {
                return ResourceManager.GetString("ConfigIssueSessionPathNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;session.save_path&quot; sets the path to the directory where PHP session data will be stored. It is recommended to use an absolute path to the directory that is writable by the web server..
        /// </summary>
        internal static string ConfigIssueSessionPathRecommend {
            get {
                return ResourceManager.GetString("ConfigIssueSessionPathRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHP directive &quot;upload_tmp_dir&quot; points to a directory that does not exist..
        /// </summary>
        internal static string ConfigIssueUploadDirNotCorrect {
            get {
                return ResourceManager.GetString("ConfigIssueUploadDirNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHP directive &quot;upload_tmp_dir&quot; is not set..
        /// </summary>
        internal static string ConfigIssueUploadDirNotSet {
            get {
                return ResourceManager.GetString("ConfigIssueUploadDirNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;upload_tmp_dir&quot; specifies the temporary directory used for storing files when doing file upload. The directory must be writable by whatever user PHP is running as..
        /// </summary>
        internal static string ConfigIssueUploadDirRecommend {
            get {
                return ResourceManager.GetString("ConfigIssueUploadDirRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete16 {
            get {
                object obj = ResourceManager.GetObject("Delete16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add PHP extension. The extension file cannot be copied to the PHP extensions directory..
        /// </summary>
        internal static string ErrorCannotAddExtension {
            get {
                return ResourceManager.GetString("ErrorCannotAddExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a temporary phpinfo file on the server due to insufficient privileges..
        /// </summary>
        internal static string ErrorCannotCreatePHPInfo {
            get {
                return ResourceManager.GetString("ErrorCannotCreatePHPInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This extension already exists in PHP extentions directory. Use &quot;Enable or disable an extension&quot; task to enable this extension..
        /// </summary>
        internal static string ErrorExtensionFileAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorExtensionFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about PHP cannot be obtained due to invalid IIS configuration..
        /// </summary>
        internal static string ErrorFailedToGetConfiguration {
            get {
                return ResourceManager.GetString("ErrorFailedToGetConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} does not exist..
        /// </summary>
        internal static string ErrorFileDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided path should point to either php-cgi.exe or php.exe..
        /// </summary>
        internal static string ErrorInvalidPHPExecutablePath {
            get {
                return ResourceManager.GetString("ErrorInvalidPHPExecutablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file (*.log)|*.log|All files (*.*)|*.*.
        /// </summary>
        internal static string ErrorLogSaveDialogFilter {
            get {
                return ResourceManager.GetString("ErrorLogSaveDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Error Log File.
        /// </summary>
        internal static string ErrorLogSaveDialogTitle {
            get {
                return ResourceManager.GetString("ErrorLogSaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory does not contain ext subdirectory with PHP extensions..
        /// </summary>
        internal static string ErrorNoExtDirectory {
            get {
                return ResourceManager.GetString("ErrorNoExtDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory does not contain required PHP files: php-cgi.exe and php.ini..
        /// </summary>
        internal static string ErrorNoPHPFilesInDirectory {
            get {
                return ResourceManager.GetString("ErrorNoPHPFilesInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The php.ini file cannot be found. Make sure PHP is correctly registered with IIS..
        /// </summary>
        internal static string ErrorPHPIniNotFound {
            get {
                return ResourceManager.GetString("ErrorPHPIniNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find PHP registration on this IIS server. PHP is either not registered or is registered incorrectly..
        /// </summary>
        internal static string ErrorPHPIsNotRegistered {
            get {
                return ResourceManager.GetString("ErrorPHPIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error log file:.
        /// </summary>
        internal static string ErrorReportingErrorLogFile {
            get {
                return ResourceManager.GetString("ErrorReportingErrorLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP error reporting and logging.
        /// </summary>
        internal static string ErrorReportingPageDescription {
            get {
                return ResourceManager.GetString("ErrorReportingPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Development machine.
        /// </summary>
        internal static string ErrorReportingPageDevMachine {
            get {
                return ResourceManager.GetString("ErrorReportingPageDevMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a development machine. A verbose error reporting will be used. All errors, warnings and informational notices will be output in a web browser and also will be written into a log file..
        /// </summary>
        internal static string ErrorReportingPageDevMachineDesc {
            get {
                return ResourceManager.GetString("ErrorReportingPageDevMachineDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error log file:.
        /// </summary>
        internal static string ErrorReportingPageErrorLogFile {
            get {
                return ResourceManager.GetString("ErrorReportingPageErrorLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this feature to configure how PHP reports and logs errors, warnings and information notices..
        /// </summary>
        internal static string ErrorReportingPageLongDescription {
            get {
                return ResourceManager.GetString("ErrorReportingPageLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Production machine.
        /// </summary>
        internal static string ErrorReportingPageProdMachine {
            get {
                return ResourceManager.GetString("ErrorReportingPageProdMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a production server accessible from the internet. Only errors will be written to a log file. No errors, warnings or notices will be output in a web browser..
        /// </summary>
        internal static string ErrorReportingPageProdMachineDesc {
            get {
                return ResourceManager.GetString("ErrorReportingPageProdMachineDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a server type. This will influence how the errors will be reported and logged..
        /// </summary>
        internal static string ErrorReportingPageSelectServerType {
            get {
                return ResourceManager.GetString("ErrorReportingPageSelectServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of server.
        /// </summary>
        internal static string ErrorReportingPageServerType {
            get {
                return ResourceManager.GetString("ErrorReportingPageServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Error Reporting.
        /// </summary>
        internal static string ErrorReportingPageTitle {
            get {
                return ResourceManager.GetString("ErrorReportingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHP version cannot be changed because some of the IIS handler mappings are locked on a server level..
        /// </summary>
        internal static string ErrorSomeHandlersLocked {
            get {
                return ResourceManager.GetString("ErrorSomeHandlersLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoBack16 {
            get {
                object obj = ResourceManager.GetObject("GoBack16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an extension.
        /// </summary>
        internal static string PHPExtensionItemAddTask {
            get {
                return ResourceManager.GetString("PHPExtensionItemAddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure extension&apos;s settings.
        /// </summary>
        internal static string PHPExtensionItemConfigureTask {
            get {
                return ResourceManager.GetString("PHPExtensionItemConfigureTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable an extension.
        /// </summary>
        internal static string PHPExtensionItemEnableTask {
            get {
                return ResourceManager.GetString("PHPExtensionItemEnableTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View enabled and disabled extensions.
        /// </summary>
        internal static string PHPExtensionItemReadOnlyEnableTask {
            get {
                return ResourceManager.GetString("PHPExtensionItemReadOnlyEnableTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PHPExtensions32 {
            get {
                object obj = ResourceManager.GetObject("PHPExtensions32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Extensions.
        /// </summary>
        internal static string PHPExtensionsItemTitle {
            get {
                return ResourceManager.GetString("PHPExtensionsItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the output of the phpinfo() function.
        /// </summary>
        internal static string PHPInfoPageDescription {
            get {
                return ResourceManager.GetString("PHPInfoPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has local handler mappings that overwrite the mappings defined on the upper levels. Changes to the PHP setup on upper levels may not take effect on this folder..
        /// </summary>
        internal static string PHPInfoPageLocalHandlersFolder {
            get {
                return ResourceManager.GetString("PHPInfoPageLocalHandlersFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has local handler mappings that overwrite the mappings defined on the server level. Changes to the PHP setup on the server level may not take effect on this site..
        /// </summary>
        internal static string PHPInfoPageLocalHandlersSite {
            get {
                return ResourceManager.GetString("PHPInfoPageLocalHandlersSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the output of phpinfo() function that provides the information about current state of PHP. This information can be used to examine all aspects of PHP runtime and for debugging purposes..
        /// </summary>
        internal static string PHPInfoPageLongDescription {
            get {
                return ResourceManager.GetString("PHPInfoPageLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phpinfo() output.
        /// </summary>
        internal static string PHPInfoPageTitle {
            get {
                return ResourceManager.GetString("PHPInfoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh phpinfo.
        /// </summary>
        internal static string PHPInfoRefreshPHPInfo {
            get {
                return ResourceManager.GetString("PHPInfoRefreshPHPInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this setting?.
        /// </summary>
        internal static string PHPIniSettingDeleteConfirmation {
            get {
                return ResourceManager.GetString("PHPIniSettingDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PHPLogo16 {
            get {
                object obj = ResourceManager.GetObject("PHPLogo16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PHPLogo32 {
            get {
                object obj = ResourceManager.GetObject("PHPLogo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file:.
        /// </summary>
        internal static string PHPPageConfigurationFile {
            get {
                return ResourceManager.GetString("PHPPageConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP runtime configuration and settings.
        /// </summary>
        internal static string PHPPageDescription {
            get {
                return ResourceManager.GetString("PHPPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} extensions enabled..
        /// </summary>
        internal static string PHPPageEnabledExtensions {
            get {
                return ResourceManager.GetString("PHPPageEnabledExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error log:.
        /// </summary>
        internal static string PHPPageErrorLog {
            get {
                return ResourceManager.GetString("PHPPageErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP executable:.
        /// </summary>
        internal static string PHPPageExecutable {
            get {
                return ResourceManager.GetString("PHPPageExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP extensions are not available.
        /// </summary>
        internal static string PHPPageExtensionsNotAvailable {
            get {
                return ResourceManager.GetString("PHPPageExtensionsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions path:.
        /// </summary>
        internal static string PHPPageExtensionsPath {
            get {
                return ResourceManager.GetString("PHPPageExtensionsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler mapping:.
        /// </summary>
        internal static string PHPPageHandlerMapping {
            get {
                return ResourceManager.GetString("PHPPageHandlerMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherited.
        /// </summary>
        internal static string PHPPageInheritedHandler {
            get {
                return ResourceManager.GetString("PHPPageInheritedHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} extensions installed..
        /// </summary>
        internal static string PHPPageInstalledExtensions {
            get {
                return ResourceManager.GetString("PHPPageInstalledExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  | .
        /// </summary>
        internal static string PHPPageItemTaskSeparator {
            get {
                return ResourceManager.GetString("PHPPageItemTaskSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string PHPPageLocalHandler {
            get {
                return ResourceManager.GetString("PHPPageLocalHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this feature to check the PHP runtime settings, to configure PHP runtime directives and to enable or disable PHP extensions..
        /// </summary>
        internal static string PHPPageLongDescription {
            get {
                return ResourceManager.GetString("PHPPageLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        internal static string PHPPagePHPNotAvailable {
            get {
                return ResourceManager.GetString("PHPPagePHPNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Manager.
        /// </summary>
        internal static string PHPPageTitle {
            get {
                return ResourceManager.GetString("PHPPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP version:.
        /// </summary>
        internal static string PHPPageVersion {
            get {
                return ResourceManager.GetString("PHPPageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PHPSettings32 {
            get {
                object obj = ResourceManager.GetObject("PHPSettings32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage all settings.
        /// </summary>
        internal static string PHPSettingsItemAllSettingsTask {
            get {
                return ResourceManager.GetString("PHPSettingsItemAllSettingsTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure error reporting.
        /// </summary>
        internal static string PHPSettingsItemErrorReportingTask {
            get {
                return ResourceManager.GetString("PHPSettingsItemErrorReportingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set runtime limits.
        /// </summary>
        internal static string PHPSettingsItemLimitsTask {
            get {
                return ResourceManager.GetString("PHPSettingsItemLimitsTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all settings.
        /// </summary>
        internal static string PHPSettingsItemReadOnlyAllSettingsTask {
            get {
                return ResourceManager.GetString("PHPSettingsItemReadOnlyAllSettingsTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View error reporting.
        /// </summary>
        internal static string PHPSettingsItemReadOnlyErrorReportingTask {
            get {
                return ResourceManager.GetString("PHPSettingsItemReadOnlyErrorReportingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View runtime limits.
        /// </summary>
        internal static string PHPSettingsItemReadOnlyLimitsTask {
            get {
                return ResourceManager.GetString("PHPSettingsItemReadOnlyLimitsTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Settings.
        /// </summary>
        internal static string PHPSettingsItemTitle {
            get {
                return ResourceManager.GetString("PHPSettingsItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PHPSetup32 {
            get {
                object obj = ResourceManager.GetObject("PHPSetup32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PHP version.
        /// </summary>
        internal static string PHPSetupItemChangeVersionTask {
            get {
                return ResourceManager.GetString("PHPSetupItemChangeVersionTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check phpinfo().
        /// </summary>
        internal static string PHPSetupItemCheckPHPInfoTask {
            get {
                return ResourceManager.GetString("PHPSetupItemCheckPHPInfoTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new PHP version.
        /// </summary>
        internal static string PHPSetupItemRegisterPHPTask {
            get {
                return ResourceManager.GetString("PHPSetupItemRegisterPHPTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Setup.
        /// </summary>
        internal static string PHPSetupItemTitle {
            get {
                return ResourceManager.GetString("PHPSetupItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current value.
        /// </summary>
        internal static string RecommendConfigDialogCurrentValue {
            get {
                return ResourceManager.GetString("RecommendConfigDialogCurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the IIS and PHP configuration issues detected on this server. Select the issues that you want to get fixed..
        /// </summary>
        internal static string RecommendConfigDialogDescription {
            get {
                return ResourceManager.GetString("RecommendConfigDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Detected configuration issues:.
        /// </summary>
        internal static string RecommendConfigDialogDetectedIssues {
            get {
                return ResourceManager.GetString("RecommendConfigDialogDetectedIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Issue description:.
        /// </summary>
        internal static string RecommendConfigDialogIssueDescription {
            get {
                return ResourceManager.GetString("RecommendConfigDialogIssueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Recommendation:.
        /// </summary>
        internal static string RecommendConfigDialogRecommendation {
            get {
                return ResourceManager.GetString("RecommendConfigDialogRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended value.
        /// </summary>
        internal static string RecommendConfigDialogRecommendedValue {
            get {
                return ResourceManager.GetString("RecommendConfigDialogRecommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting name.
        /// </summary>
        internal static string RecommendConfigDialogSettingName {
            get {
                return ResourceManager.GetString("RecommendConfigDialogSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Recommendations.
        /// </summary>
        internal static string RecommendConfigDialogTitle {
            get {
                return ResourceManager.GetString("RecommendConfigDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: C:\PHP\php-cgi.exe.
        /// </summary>
        internal static string RegisterPHPDialogExample {
            get {
                return ResourceManager.GetString("RegisterPHPDialogExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP executable (php-cgi.exe)|php-cgi.exe|All files (*.*)|*.*.
        /// </summary>
        internal static string RegisterPHPDialogOpenFileFilter {
            get {
                return ResourceManager.GetString("RegisterPHPDialogOpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select PHP executable file.
        /// </summary>
        internal static string RegisterPHPDialogOpenFileTitle {
            get {
                return ResourceManager.GetString("RegisterPHPDialogOpenFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new PHP version.
        /// </summary>
        internal static string RegisterPHPDialogRegisterNew {
            get {
                return ResourceManager.GetString("RegisterPHPDialogRegisterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a path to the php executable file (php-cgi.exe):.
        /// </summary>
        internal static string RegisterPHPDialogSelectPath {
            get {
                return ResourceManager.GetString("RegisterPHPDialogSelectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Handling.
        /// </summary>
        internal static string RuntimeLimitsDataHandling {
            get {
                return ResourceManager.GetString("RuntimeLimitsDataHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Execution Time.
        /// </summary>
        internal static string RuntimeLimitsMaxExecutionTime {
            get {
                return ResourceManager.GetString("RuntimeLimitsMaxExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum time in seconds a script is allowed to run before it is terminated by the parser. This helps prevent poorly written scripts from tying up the server..
        /// </summary>
        internal static string RuntimeLimitsMaxExecutionTimeDescription {
            get {
                return ResourceManager.GetString("RuntimeLimitsMaxExecutionTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Files To Upload.
        /// </summary>
        internal static string RuntimeLimitsMaxFileUploads {
            get {
                return ResourceManager.GetString("RuntimeLimitsMaxFileUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of files that can be uploaded via a single request..
        /// </summary>
        internal static string RuntimeLimitsMaxFileUploadsDescription {
            get {
                return ResourceManager.GetString("RuntimeLimitsMaxFileUploadsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Input Time.
        /// </summary>
        internal static string RuntimeLimitsMaxInputTime {
            get {
                return ResourceManager.GetString("RuntimeLimitsMaxInputTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum time in seconds a script is allowed to parse input data, like POST, GET and file uploads..
        /// </summary>
        internal static string RuntimeLimitsMaxInputTimeDescription {
            get {
                return ResourceManager.GetString("RuntimeLimitsMaxInputTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Limit.
        /// </summary>
        internal static string RuntimeLimitsMemoryLimit {
            get {
                return ResourceManager.GetString("RuntimeLimitsMemoryLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum amount of memory in bytes that a script is allowed to allocate. This helps prevent poorly written scripts for eating up all available memory on a server..
        /// </summary>
        internal static string RuntimeLimitsMemoryLimitDescription {
            get {
                return ResourceManager.GetString("RuntimeLimitsMemoryLimitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure PHP runtime limits, including execution timeouts, maximum upload times, etc..
        /// </summary>
        internal static string RuntimeLimitsPageDescription {
            get {
                return ResourceManager.GetString("RuntimeLimitsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure PHP runtime limits, such as maximum script execution time, maximum size of uploaded files, request timeouts and others..
        /// </summary>
        internal static string RuntimeLimitsPageLongDescription {
            get {
                return ResourceManager.GetString("RuntimeLimitsPageLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Runtime Limits.
        /// </summary>
        internal static string RuntimeLimitsPageTitle {
            get {
                return ResourceManager.GetString("RuntimeLimitsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum POST size.
        /// </summary>
        internal static string RuntimeLimitsPostMaxSize {
            get {
                return ResourceManager.GetString("RuntimeLimitsPostMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed size of POST data. This setting also affects file upload. To upload large files, this value must be larger than upload_max_filesize..
        /// </summary>
        internal static string RuntimeLimitsPostMaxSizeDescription {
            get {
                return ResourceManager.GetString("RuntimeLimitsPostMaxSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Limits.
        /// </summary>
        internal static string RuntimeLimitsResourceLimits {
            get {
                return ResourceManager.GetString("RuntimeLimitsResourceLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Maximum File Size.
        /// </summary>
        internal static string RuntimeLimitsUploadMaxFilesize {
            get {
                return ResourceManager.GetString("RuntimeLimitsUploadMaxFilesize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed size for uploaded files..
        /// </summary>
        internal static string RuntimeLimitsUploadMaxFilesizeDescription {
            get {
                return ResourceManager.GetString("RuntimeLimitsUploadMaxFilesizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a &amp;site where to check PHP configuration:.
        /// </summary>
        internal static string SelectSiteAndUrlDialogSelectASite {
            get {
                return ResourceManager.GetString("SelectSiteAndUrlDialogSelectASite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a &amp;URL used for the selected site:.
        /// </summary>
        internal static string SelectSiteAndUrlDialogSelectAUrl {
            get {
                return ResourceManager.GetString("SelectSiteAndUrlDialogSelectAUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Site and URL.
        /// </summary>
        internal static string SelectSiteAndUrlDialogTitle {
            get {
                return ResourceManager.GetString("SelectSiteAndUrlDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Warning16 {
            get {
                object obj = ResourceManager.GetObject("Warning16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more..
        /// </summary>
        internal static string WarningFastCgiLearnMore {
            get {
                return ResourceManager.GetString("WarningFastCgiLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not optimal PHP registration (CGI) is found. Register new PHP version to enable PHP via FastCGI..
        /// </summary>
        internal static string WarningPHPConfigCgi {
            get {
                return ResourceManager.GetString("WarningPHPConfigCgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not optimal PHP registration (ISAPI) is found. Register new PHP version to enable PHP via FastCGI..
        /// </summary>
        internal static string WarningPHPConfigIsapi {
            get {
                return ResourceManager.GetString("WarningPHPConfigIsapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FastCGI feature must be enabled in order to register PHP. .
        /// </summary>
        internal static string WarningPHPConfigNoFastCgi {
            get {
                return ResourceManager.GetString("WarningPHPConfigNoFastCgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not optimal PHP configuration detected on this machine. .
        /// </summary>
        internal static string WarningPHPConfigNotOptimal {
            get {
                return ResourceManager.GetString("WarningPHPConfigNotOptimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP is not enabled. Register new PHP version to enable PHP via FastCGI..
        /// </summary>
        internal static string WarningPHPConfigNotRegistered {
            get {
                return ResourceManager.GetString("WarningPHPConfigNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View recommendations..
        /// </summary>
        internal static string WarningViewRecommendations {
            get {
                return ResourceManager.GetString("WarningViewRecommendations", resourceCulture);
            }
        }
    }
}
