//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Management.PHP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Management.PHP.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add PHP Setting.
        /// </summary>
        internal static string AddPHPSetting {
            get {
                return ResourceManager.GetString("AddPHPSetting", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Delete16 {
            get {
                object obj = ResourceManager.GetObject("Delete16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string DisableExtension {
            get {
                return ResourceManager.GetString("DisableExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit PHP Setting.
        /// </summary>
        internal static string EditPHPSetting {
            get {
                return ResourceManager.GetString("EditPHPSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit....
        /// </summary>
        internal static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string EnableExtension {
            get {
                return ResourceManager.GetString("EnableExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting extensions.
        /// </summary>
        internal static string GettingExtensions {
            get {
                return ResourceManager.GetString("GettingExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting settings.
        /// </summary>
        internal static string GettingSettings {
            get {
                return ResourceManager.GetString("GettingSettings", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap GoBack16 {
            get {
                object obj = ResourceManager.GetObject("GoBack16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to main page.
        /// </summary>
        internal static string GoBackTask {
            get {
                return ResourceManager.GetString("GoBackTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameActionColumnText {
            get {
                return ResourceManager.GetString("NameActionColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory does not contain required PHP files: php-cgi.exe and php.ini..
        /// </summary>
        internal static string NoPHPFilesInDirectory {
            get {
                return ResourceManager.GetString("NoPHPFilesInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open php.ini.
        /// </summary>
        internal static string OpenPHPIniFile {
            get {
                return ResourceManager.GetString("OpenPHPIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure extension&apos;s settings.
        /// </summary>
        internal static string PHPExtensionConfigure {
            get {
                return ResourceManager.GetString("PHPExtensionConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable an extension.
        /// </summary>
        internal static string PHPExtensionEnableDisable {
            get {
                return ResourceManager.GetString("PHPExtensionEnableDisable", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PHPExtensions32 {
            get {
                object obj = ResourceManager.GetObject("PHPExtensions32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable PHP extensions and configure PHP extensions settings..
        /// </summary>
        internal static string PHPExtensionsPageDescription {
            get {
                return ResourceManager.GetString("PHPExtensionsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string PHPExtensionsPageFileNameColumnText {
            get {
                return ResourceManager.GetString("PHPExtensionsPageFileNameColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable PHP extensions and configure PHP extensions settings..
        /// </summary>
        internal static string PHPExtensionsPageLongDescription {
            get {
                return ResourceManager.GetString("PHPExtensionsPageLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PHPExtensionsPageNameColumnText {
            get {
                return ResourceManager.GetString("PHPExtensionsPageNameColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string PHPExtensionsPageStateColumnText {
            get {
                return ResourceManager.GetString("PHPExtensionsPageStateColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Extensions.
        /// </summary>
        internal static string PHPExtensionsPageTitle {
            get {
                return ResourceManager.GetString("PHPExtensionsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the the output of phpinfo() function that provides the information about current state of PHP. This information can be used to examine all aspects of PHP runtime and for debugging purposes..
        /// </summary>
        internal static string PHPInfoLongDescription {
            get {
                return ResourceManager.GetString("PHPInfoLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the output of the phpinfo() function.
        /// </summary>
        internal static string PHPInfoPageDescription {
            get {
                return ResourceManager.GetString("PHPInfoPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phpinfo() output.
        /// </summary>
        internal static string PHPInfoPageTitle {
            get {
                return ResourceManager.GetString("PHPInfoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh phpinfo.
        /// </summary>
        internal static string PHPInfoRefreshPHPInfo {
            get {
                return ResourceManager.GetString("PHPInfoRefreshPHPInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select domain....
        /// </summary>
        internal static string PHPInfoSelectDomain {
            get {
                return ResourceManager.GetString("PHPInfoSelectDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to php.ini file does not exist.
        /// </summary>
        internal static string PHPIniFileDoesNotExist {
            get {
                return ResourceManager.GetString("PHPIniFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this setting?.
        /// </summary>
        internal static string PHPIniSettingDeleteConfirmation {
            get {
                return ResourceManager.GetString("PHPIniSettingDeleteConfirmation", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PHPLogo16 {
            get {
                object obj = ResourceManager.GetObject("PHPLogo16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PHPLogo32 {
            get {
                object obj = ResourceManager.GetObject("PHPLogo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP runtime configuration and settings.
        /// </summary>
        internal static string PHPPageDescription {
            get {
                return ResourceManager.GetString("PHPPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  | .
        /// </summary>
        internal static string PHPPageItemTaskSeparator {
            get {
                return ResourceManager.GetString("PHPPageItemTaskSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this feature to check the PHP runtime settings, to configure PHP runtime directives and to enabled and disable PHP extensions..
        /// </summary>
        internal static string PHPPageLongDescription {
            get {
                return ResourceManager.GetString("PHPPageLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Manager.
        /// </summary>
        internal static string PHPPageTitle {
            get {
                return ResourceManager.GetString("PHPPageTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PHPSettings32 {
            get {
                object obj = ResourceManager.GetObject("PHPSettings32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage all PHP runtime settings.
        /// </summary>
        internal static string PHPSettingsAllSettingsTask {
            get {
                return ResourceManager.GetString("PHPSettingsAllSettingsTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply recommended settings.
        /// </summary>
        internal static string PHPSettingsApplyRecommendedTask {
            get {
                return ResourceManager.GetString("PHPSettingsApplyRecommendedTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure error reporting.
        /// </summary>
        internal static string PHPSettingsErrorReportingTask {
            get {
                return ResourceManager.GetString("PHPSettingsErrorReportingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check and edit PHP runtime settings, such as error logging, include directories, session, security and more.
        /// </summary>
        internal static string PHPSettingsLongDescription {
            get {
                return ResourceManager.GetString("PHPSettingsLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        internal static string PHPSettingsPageAddDirectiveTask {
            get {
                return ResourceManager.GetString("PHPSettingsPageAddDirectiveTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure all php settings.
        /// </summary>
        internal static string PHPSettingsPageDescription {
            get {
                return ResourceManager.GetString("PHPSettingsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure all php settings.
        /// </summary>
        internal static string PHPSettingsPageLongDescription {
            get {
                return ResourceManager.GetString("PHPSettingsPageLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PHPSettingsPageNameColumnText {
            get {
                return ResourceManager.GetString("PHPSettingsPageNameColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string PHPSettingsPageSectionColumnText {
            get {
                return ResourceManager.GetString("PHPSettingsPageSectionColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Settings.
        /// </summary>
        internal static string PHPSettingsPageTitle {
            get {
                return ResourceManager.GetString("PHPSettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string PHPSettingsPageValueColumnText {
            get {
                return ResourceManager.GetString("PHPSettingsPageValueColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Settings.
        /// </summary>
        internal static string PHPSettingsTitle {
            get {
                return ResourceManager.GetString("PHPSettingsTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PHPSetup32 {
            get {
                object obj = ResourceManager.GetObject("PHPSetup32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PHP version.
        /// </summary>
        internal static string PHPSetupChangeVersion {
            get {
                return ResourceManager.GetString("PHPSetupChangeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check phpinfo().
        /// </summary>
        internal static string PHPSetupCheckPHPInfoTask {
            get {
                return ResourceManager.GetString("PHPSetupCheckPHPInfoTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this feature to configure IIS to work with PHP, to check that PHP and IIS are configured correctly and to select the PHP version, if more than one version is installed on the server..
        /// </summary>
        internal static string PHPSetupLongDescription {
            get {
                return ResourceManager.GetString("PHPSetupLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure IIS to properly work with PHP.
        /// </summary>
        internal static string PHPSetupPageDescription {
            get {
                return ResourceManager.GetString("PHPSetupPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Setup.
        /// </summary>
        internal static string PHPSetupPageTitle {
            get {
                return ResourceManager.GetString("PHPSetupPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new PHP version.
        /// </summary>
        internal static string PHPSetupRegisterPHPTask {
            get {
                return ResourceManager.GetString("PHPSetupRegisterPHPTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder where PHP runtime binaries and PHP configuration file are located..
        /// </summary>
        internal static string PHPSetupSelectFolderDescription {
            get {
                return ResourceManager.GetString("PHPSetupSelectFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string RemoveTitle {
            get {
                return ResourceManager.GetString("RemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string SectionActionColumnText {
            get {
                return ResourceManager.GetString("SectionActionColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Domain:.
        /// </summary>
        internal static string SelectDomainDomainLabel {
            get {
                return ResourceManager.GetString("SelectDomainDomainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a domain name used for this site..
        /// </summary>
        internal static string SelectDomainSelectADomainFirst {
            get {
                return ResourceManager.GetString("SelectDomainSelectADomainFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Domain.
        /// </summary>
        internal static string SelectDomainTitle {
            get {
                return ResourceManager.GetString("SelectDomainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use this feature, you must first select a site..
        /// </summary>
        internal static string SelectSiteSelectASiteFirst {
            get {
                return ResourceManager.GetString("SelectSiteSelectASiteFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Site:.
        /// </summary>
        internal static string SelectSiteSiteLabel {
            get {
                return ResourceManager.GetString("SelectSiteSiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Site.
        /// </summary>
        internal static string SelectSiteTitle {
            get {
                return ResourceManager.GetString("SelectSiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about this setting.
        /// </summary>
        internal static string SettingLearnMoreLinkLabel {
            get {
                return ResourceManager.GetString("SettingLearnMoreLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string SettingNameLabel {
            get {
                return ResourceManager.GetString("SettingNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section:.
        /// </summary>
        internal static string SettingSectionLabel {
            get {
                return ResourceManager.GetString("SettingSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        internal static string SettingValueLabel {
            get {
                return ResourceManager.GetString("SettingValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string StateActionColumnText {
            get {
                return ResourceManager.GetString("StateActionColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ValueActionColumnText {
            get {
                return ResourceManager.GetString("ValueActionColumnText", resourceCulture);
            }
        }
    }
}
