//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Management.PHP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Management.PHP.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add PHP Setting.
        /// </summary>
        internal static string AddEditSettingDialogAddSetting {
            get {
                return ResourceManager.GetString("AddEditSettingDialogAddSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit PHP Setting.
        /// </summary>
        internal static string AddEditSettingDialogEditSetting {
            get {
                return ResourceManager.GetString("AddEditSettingDialogEditSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about this setting.
        /// </summary>
        internal static string AddEditSettingDialogLearnMore {
            get {
                return ResourceManager.GetString("AddEditSettingDialogLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string AddEditSettingDialogName {
            get {
                return ResourceManager.GetString("AddEditSettingDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section:.
        /// </summary>
        internal static string AddEditSettingDialogSection {
            get {
                return ResourceManager.GetString("AddEditSettingDialogSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        internal static string AddEditSettingDialogValue {
            get {
                return ResourceManager.GetString("AddEditSettingDialogValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable PHP extensions and configure PHP extensions settings..
        /// </summary>
        internal static string AllExtensionsPageDescription {
            get {
                return ResourceManager.GetString("AllExtensionsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string AllExtensionsPageDisabledGroup {
            get {
                return ResourceManager.GetString("AllExtensionsPageDisabledGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string AllExtensionsPageDisableTask {
            get {
                return ResourceManager.GetString("AllExtensionsPageDisableTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string AllExtensionsPageEnabledGroup {
            get {
                return ResourceManager.GetString("AllExtensionsPageEnabledGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string AllExtensionsPageEnableTask {
            get {
                return ResourceManager.GetString("AllExtensionsPageEnableTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting extensions.
        /// </summary>
        internal static string AllExtensionsPageGettingExtensions {
            get {
                return ResourceManager.GetString("AllExtensionsPageGettingExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP extensions provide additional functionality to PHP runtime, such as database connectivity, caching, debugging and others. Use this feature to enable or disable PHP extensions and to configure PHP extensions settings..
        /// </summary>
        internal static string AllExtensionsPageLongDescription {
            get {
                return ResourceManager.GetString("AllExtensionsPageLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string AllExtensionsPageNameField {
            get {
                return ResourceManager.GetString("AllExtensionsPageNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string AllExtensionsPageStateField {
            get {
                return ResourceManager.GetString("AllExtensionsPageStateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Extensions.
        /// </summary>
        internal static string AllExtensionsPageTitle {
            get {
                return ResourceManager.GetString("AllExtensionsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to main page.
        /// </summary>
        internal static string AllPagesGoBackTask {
            get {
                return ResourceManager.GetString("AllPagesGoBackTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open php.ini.
        /// </summary>
        internal static string AllPagesOpenPHPIniTask {
            get {
                return ResourceManager.GetString("AllPagesOpenPHPIniTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These settings are read-only. They can only be changed by a server administrator..
        /// </summary>
        internal static string AllPagesPageIsReadOnly {
            get {
                return ResourceManager.GetString("AllPagesPageIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        internal static string AllSettingsPageAddSettingTask {
            get {
                return ResourceManager.GetString("AllSettingsPageAddSettingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure all php settings.
        /// </summary>
        internal static string AllSettingsPageDescription {
            get {
                return ResourceManager.GetString("AllSettingsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit....
        /// </summary>
        internal static string AllSettingsPageEditTask {
            get {
                return ResourceManager.GetString("AllSettingsPageEditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting settings.
        /// </summary>
        internal static string AllSettingsPageGettingSettings {
            get {
                return ResourceManager.GetString("AllSettingsPageGettingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure all php settings that are stored in php.ini file. These setting control all aspects of PHP runtime, such error reporting, security, sessions and others..
        /// </summary>
        internal static string AllSettingsPageLongDescription {
            get {
                return ResourceManager.GetString("AllSettingsPageLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string AllSettingsPageNameField {
            get {
                return ResourceManager.GetString("AllSettingsPageNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string AllSettingsPageRemoveTask {
            get {
                return ResourceManager.GetString("AllSettingsPageRemoveTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string AllSettingsPageSectionField {
            get {
                return ResourceManager.GetString("AllSettingsPageSectionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Settings.
        /// </summary>
        internal static string AllSettingsPageTitle {
            get {
                return ResourceManager.GetString("AllSettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string AllSettingsPageValueField {
            get {
                return ResourceManager.GetString("AllSettingsPageValueField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select PHP version:.
        /// </summary>
        internal static string ChangeVersionDialogSelectVersion {
            get {
                return ResourceManager.GetString("ChangeVersionDialogSelectVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PHP version.
        /// </summary>
        internal static string ChangeVersionDialogTitle {
            get {
                return ResourceManager.GetString("ChangeVersionDialogTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Delete16 {
            get {
                object obj = ResourceManager.GetObject("Delete16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a temporary phpinfo file on the server due to insufficient privileges..
        /// </summary>
        internal static string ErrorCannotCreatePHPInfo {
            get {
                return ResourceManager.GetString("ErrorCannotCreatePHPInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} does not exist..
        /// </summary>
        internal static string ErrorFileDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided path does not point to either php-cgi.exe or php.exe..
        /// </summary>
        internal static string ErrorInvalidPHPExecutablePath {
            get {
                return ResourceManager.GetString("ErrorInvalidPHPExecutablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file (*.log)|*.log|All files (*.*)|*.*.
        /// </summary>
        internal static string ErrorLogSaveDialogFilter {
            get {
                return ResourceManager.GetString("ErrorLogSaveDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Error Log File.
        /// </summary>
        internal static string ErrorLogSaveDialogTitle {
            get {
                return ResourceManager.GetString("ErrorLogSaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory does not contain ext subdirectory with PHP extensions..
        /// </summary>
        internal static string ErrorNoExtDirectory {
            get {
                return ResourceManager.GetString("ErrorNoExtDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory does not contain required PHP files: php-cgi.exe and php.ini..
        /// </summary>
        internal static string ErrorNoPHPFilesInDirectory {
            get {
                return ResourceManager.GetString("ErrorNoPHPFilesInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The php.ini file cannot be found. Make sure PHP is correctly regestered with IIS..
        /// </summary>
        internal static string ErrorPHPIniNotFound {
            get {
                return ResourceManager.GetString("ErrorPHPIniNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error log file:.
        /// </summary>
        internal static string ErrorReportingErrorLogFile {
            get {
                return ResourceManager.GetString("ErrorReportingErrorLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP error reporting and logging.
        /// </summary>
        internal static string ErrorReportingPageDescription {
            get {
                return ResourceManager.GetString("ErrorReportingPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Development machine.
        /// </summary>
        internal static string ErrorReportingPageDevMachine {
            get {
                return ResourceManager.GetString("ErrorReportingPageDevMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a development machine. A verbose error reporting will be used. All errors, warnings and informational notices will be output in a web browser and also will be written into a log file..
        /// </summary>
        internal static string ErrorReportingPageDevMachineDesc {
            get {
                return ResourceManager.GetString("ErrorReportingPageDevMachineDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error log file:.
        /// </summary>
        internal static string ErrorReportingPageErrorLogFile {
            get {
                return ResourceManager.GetString("ErrorReportingPageErrorLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this feature to configure how PHP reports and logs errors, warnings and information notices..
        /// </summary>
        internal static string ErrorReportingPageLongDescription {
            get {
                return ResourceManager.GetString("ErrorReportingPageLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Production machine.
        /// </summary>
        internal static string ErrorReportingPageProdMachine {
            get {
                return ResourceManager.GetString("ErrorReportingPageProdMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a production server accessible from the internet. Only errors will be written to a log file. No errors, warnings or notices will be output in a web browser..
        /// </summary>
        internal static string ErrorReportingPageProdMachineDesc {
            get {
                return ResourceManager.GetString("ErrorReportingPageProdMachineDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a server type. This will influence how the errors will be reported and logged..
        /// </summary>
        internal static string ErrorReportingPageSelectServerType {
            get {
                return ResourceManager.GetString("ErrorReportingPageSelectServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of server.
        /// </summary>
        internal static string ErrorReportingPageServerType {
            get {
                return ResourceManager.GetString("ErrorReportingPageServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Error Reporting.
        /// </summary>
        internal static string ErrorReportingPageTitle {
            get {
                return ResourceManager.GetString("ErrorReportingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PHP version cannot be changed because some of the IIS handler mappings are locked on a server level..
        /// </summary>
        internal static string ErrorSomeHandlersLocked {
            get {
                return ResourceManager.GetString("ErrorSomeHandlersLocked", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap GoBack16 {
            get {
                object obj = ResourceManager.GetObject("GoBack16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure extension&apos;s settings.
        /// </summary>
        internal static string PHPExtensionItemConfigureTask {
            get {
                return ResourceManager.GetString("PHPExtensionItemConfigureTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable an extension.
        /// </summary>
        internal static string PHPExtensionItemEnableTask {
            get {
                return ResourceManager.GetString("PHPExtensionItemEnableTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View enabled and disabled extensions.
        /// </summary>
        internal static string PHPExtensionItemReadOnlyEnableTask {
            get {
                return ResourceManager.GetString("PHPExtensionItemReadOnlyEnableTask", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PHPExtensions32 {
            get {
                object obj = ResourceManager.GetObject("PHPExtensions32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Extensions.
        /// </summary>
        internal static string PHPExtensionsItemTitle {
            get {
                return ResourceManager.GetString("PHPExtensionsItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the output of the phpinfo() function.
        /// </summary>
        internal static string PHPInfoPageDescription {
            get {
                return ResourceManager.GetString("PHPInfoPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the the output of phpinfo() function that provides the information about current state of PHP. This information can be used to examine all aspects of PHP runtime and for debugging purposes..
        /// </summary>
        internal static string PHPInfoPageLongDescription {
            get {
                return ResourceManager.GetString("PHPInfoPageLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phpinfo() output.
        /// </summary>
        internal static string PHPInfoPageTitle {
            get {
                return ResourceManager.GetString("PHPInfoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh phpinfo.
        /// </summary>
        internal static string PHPInfoRefreshPHPInfo {
            get {
                return ResourceManager.GetString("PHPInfoRefreshPHPInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this setting?.
        /// </summary>
        internal static string PHPIniSettingDeleteConfirmation {
            get {
                return ResourceManager.GetString("PHPIniSettingDeleteConfirmation", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PHPLogo16 {
            get {
                object obj = ResourceManager.GetObject("PHPLogo16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PHPLogo32 {
            get {
                object obj = ResourceManager.GetObject("PHPLogo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file:.
        /// </summary>
        internal static string PHPPageConfigurationFile {
            get {
                return ResourceManager.GetString("PHPPageConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP runtime configuration and settings.
        /// </summary>
        internal static string PHPPageDescription {
            get {
                return ResourceManager.GetString("PHPPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} extensions enabled..
        /// </summary>
        internal static string PHPPageEnabledExtensions {
            get {
                return ResourceManager.GetString("PHPPageEnabledExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error log:.
        /// </summary>
        internal static string PHPPageErrorLog {
            get {
                return ResourceManager.GetString("PHPPageErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP executable:.
        /// </summary>
        internal static string PHPPageExecutable {
            get {
                return ResourceManager.GetString("PHPPageExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP extensions are not available.
        /// </summary>
        internal static string PHPPageExtensionsNotAvailable {
            get {
                return ResourceManager.GetString("PHPPageExtensionsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions path:.
        /// </summary>
        internal static string PHPPageExtensionsPath {
            get {
                return ResourceManager.GetString("PHPPageExtensionsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} extensions installed..
        /// </summary>
        internal static string PHPPageInstalledExtensions {
            get {
                return ResourceManager.GetString("PHPPageInstalledExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  | .
        /// </summary>
        internal static string PHPPageItemTaskSeparator {
            get {
                return ResourceManager.GetString("PHPPageItemTaskSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this feature to check the PHP runtime settings, to configure PHP runtime directives and to enable or disable PHP extensions..
        /// </summary>
        internal static string PHPPageLongDescription {
            get {
                return ResourceManager.GetString("PHPPageLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        internal static string PHPPagePHPNotAvailable {
            get {
                return ResourceManager.GetString("PHPPagePHPNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available (PHP is not registered on this IIS server).
        /// </summary>
        internal static string PHPPagePHPNotRegistered {
            get {
                return ResourceManager.GetString("PHPPagePHPNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Manager.
        /// </summary>
        internal static string PHPPageTitle {
            get {
                return ResourceManager.GetString("PHPPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP version:.
        /// </summary>
        internal static string PHPPageVersion {
            get {
                return ResourceManager.GetString("PHPPageVersion", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PHPSettings32 {
            get {
                object obj = ResourceManager.GetObject("PHPSettings32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage all settings.
        /// </summary>
        internal static string PHPSettingsItemAllSettingsTask {
            get {
                return ResourceManager.GetString("PHPSettingsItemAllSettingsTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure error reporting.
        /// </summary>
        internal static string PHPSettingsItemErrorReportingTask {
            get {
                return ResourceManager.GetString("PHPSettingsItemErrorReportingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set runtime limits.
        /// </summary>
        internal static string PHPSettingsItemLimitsTask {
            get {
                return ResourceManager.GetString("PHPSettingsItemLimitsTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all settings.
        /// </summary>
        internal static string PHPSettingsItemReadOnlyAllSettingsTask {
            get {
                return ResourceManager.GetString("PHPSettingsItemReadOnlyAllSettingsTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View error reporting.
        /// </summary>
        internal static string PHPSettingsItemReadOnlyErrorReportingTask {
            get {
                return ResourceManager.GetString("PHPSettingsItemReadOnlyErrorReportingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View runtime limits.
        /// </summary>
        internal static string PHPSettingsItemReadOnlyLimitsTask {
            get {
                return ResourceManager.GetString("PHPSettingsItemReadOnlyLimitsTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Settings.
        /// </summary>
        internal static string PHPSettingsItemTitle {
            get {
                return ResourceManager.GetString("PHPSettingsItemTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PHPSetup32 {
            get {
                object obj = ResourceManager.GetObject("PHPSetup32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PHP version.
        /// </summary>
        internal static string PHPSetupItemChangeVersionTask {
            get {
                return ResourceManager.GetString("PHPSetupItemChangeVersionTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check phpinfo().
        /// </summary>
        internal static string PHPSetupItemCheckPHPInfoTask {
            get {
                return ResourceManager.GetString("PHPSetupItemCheckPHPInfoTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new PHP version.
        /// </summary>
        internal static string PHPSetupItemRegisterPHPTask {
            get {
                return ResourceManager.GetString("PHPSetupItemRegisterPHPTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Setup.
        /// </summary>
        internal static string PHPSetupItemTitle {
            get {
                return ResourceManager.GetString("PHPSetupItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: C:\PHP\php-cgi.exe.
        /// </summary>
        internal static string RegisterPHPDialogExample {
            get {
                return ResourceManager.GetString("RegisterPHPDialogExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP executable (php-cgi.exe)|php-cgi.exe|All files (*.*)|*.*.
        /// </summary>
        internal static string RegisterPHPDialogOpenFileFilter {
            get {
                return ResourceManager.GetString("RegisterPHPDialogOpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select PHP executable file.
        /// </summary>
        internal static string RegisterPHPDialogOpenFileTitle {
            get {
                return ResourceManager.GetString("RegisterPHPDialogOpenFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new PHP version.
        /// </summary>
        internal static string RegisterPHPDialogRegisterNew {
            get {
                return ResourceManager.GetString("RegisterPHPDialogRegisterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a path to the php executable file (php-cgi.exe):.
        /// </summary>
        internal static string RegisterPHPDialogSelectPath {
            get {
                return ResourceManager.GetString("RegisterPHPDialogSelectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Handling.
        /// </summary>
        internal static string RuntimeLimitsDataHandling {
            get {
                return ResourceManager.GetString("RuntimeLimitsDataHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Execution Time.
        /// </summary>
        internal static string RuntimeLimitsMaxExecutionTime {
            get {
                return ResourceManager.GetString("RuntimeLimitsMaxExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum time in seconds a script is allowed to run before it is terminated by the parser. This helps prevent poorly written scripts from tying up the server..
        /// </summary>
        internal static string RuntimeLimitsMaxExecutionTimeDescription {
            get {
                return ResourceManager.GetString("RuntimeLimitsMaxExecutionTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Files To Upload.
        /// </summary>
        internal static string RuntimeLimitsMaxFileUploads {
            get {
                return ResourceManager.GetString("RuntimeLimitsMaxFileUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of files that can be uploaded via a single request..
        /// </summary>
        internal static string RuntimeLimitsMaxFileUploadsDescription {
            get {
                return ResourceManager.GetString("RuntimeLimitsMaxFileUploadsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Input Time.
        /// </summary>
        internal static string RuntimeLimitsMaxInputTime {
            get {
                return ResourceManager.GetString("RuntimeLimitsMaxInputTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum time in seconds a script is allowed to parse input data, like POST, GET and file uploads..
        /// </summary>
        internal static string RuntimeLimitsMaxInputTimeDescription {
            get {
                return ResourceManager.GetString("RuntimeLimitsMaxInputTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Limit.
        /// </summary>
        internal static string RuntimeLimitsMemoryLimit {
            get {
                return ResourceManager.GetString("RuntimeLimitsMemoryLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum amount of memory in bytes that a script is allowed to allocate. This helps prevent poorly written scripts for eating up all available memory on a server..
        /// </summary>
        internal static string RuntimeLimitsMemoryLimitDescription {
            get {
                return ResourceManager.GetString("RuntimeLimitsMemoryLimitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure PHP runtime limits, including execution timeouts, maximum upload times, etc..
        /// </summary>
        internal static string RuntimeLimitsPageDescription {
            get {
                return ResourceManager.GetString("RuntimeLimitsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure PHP runtime limits, such as maximum script execution time, maximum size of uploaded files, request timeouts and others..
        /// </summary>
        internal static string RuntimeLimitsPageLongDescription {
            get {
                return ResourceManager.GetString("RuntimeLimitsPageLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Runtime Limits.
        /// </summary>
        internal static string RuntimeLimitsPageTitle {
            get {
                return ResourceManager.GetString("RuntimeLimitsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum POST size.
        /// </summary>
        internal static string RuntimeLimitsPostMaxSize {
            get {
                return ResourceManager.GetString("RuntimeLimitsPostMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed size of POST data. This setting also affects file upload. To upload large files, this value must be larger than upload_max_filesize..
        /// </summary>
        internal static string RuntimeLimitsPostMaxSizeDescription {
            get {
                return ResourceManager.GetString("RuntimeLimitsPostMaxSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Limits.
        /// </summary>
        internal static string RuntimeLimitsResourceLimits {
            get {
                return ResourceManager.GetString("RuntimeLimitsResourceLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Maximum File Size.
        /// </summary>
        internal static string RuntimeLimitsUploadMaxFilesize {
            get {
                return ResourceManager.GetString("RuntimeLimitsUploadMaxFilesize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed size for uploaded files..
        /// </summary>
        internal static string RuntimeLimitsUploadMaxFilesizeDescription {
            get {
                return ResourceManager.GetString("RuntimeLimitsUploadMaxFilesizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a &amp;site where to check PHP configuration:.
        /// </summary>
        internal static string SelectSiteAndUrlDialogSelectASite {
            get {
                return ResourceManager.GetString("SelectSiteAndUrlDialogSelectASite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a &amp;URL used for the selected site:.
        /// </summary>
        internal static string SelectSiteAndUrlDialogSelectAUrl {
            get {
                return ResourceManager.GetString("SelectSiteAndUrlDialogSelectAUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Site and URL.
        /// </summary>
        internal static string SelectSiteAndUrlDialogTitle {
            get {
                return ResourceManager.GetString("SelectSiteAndUrlDialogTitle", resourceCulture);
            }
        }
    }
}
