//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Management.PHP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Management.PHP.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add PHP Setting.
        /// </summary>
        internal static string AddEditSettingDialogAddSetting {
            get {
                return ResourceManager.GetString("AddEditSettingDialogAddSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit PHP Setting.
        /// </summary>
        internal static string AddEditSettingDialogEditSetting {
            get {
                return ResourceManager.GetString("AddEditSettingDialogEditSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about this setting.
        /// </summary>
        internal static string AddEditSettingDialogLearnMore {
            get {
                return ResourceManager.GetString("AddEditSettingDialogLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string AddEditSettingDialogName {
            get {
                return ResourceManager.GetString("AddEditSettingDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section:.
        /// </summary>
        internal static string AddEditSettingDialogSection {
            get {
                return ResourceManager.GetString("AddEditSettingDialogSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        internal static string AddEditSettingDialogValue {
            get {
                return ResourceManager.GetString("AddEditSettingDialogValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to main page.
        /// </summary>
        internal static string AllPagesGoBackTask {
            get {
                return ResourceManager.GetString("AllPagesGoBackTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open php.ini.
        /// </summary>
        internal static string AllPagesOpenPHPIniTask {
            get {
                return ResourceManager.GetString("AllPagesOpenPHPIniTask", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Delete16 {
            get {
                object obj = ResourceManager.GetObject("Delete16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory does not contain required PHP files: php-cgi.exe and php.ini..
        /// </summary>
        internal static string ErrorNoPHPFilesInDirectory {
            get {
                return ResourceManager.GetString("ErrorNoPHPFilesInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to php.ini file does not exist..
        /// </summary>
        internal static string ErrorPHPIniFileDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorPHPIniFileDoesNotExist", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap GoBack16 {
            get {
                object obj = ResourceManager.GetObject("GoBack16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure extension&apos;s settings.
        /// </summary>
        internal static string PHPExtensionItemConfigureTask {
            get {
                return ResourceManager.GetString("PHPExtensionItemConfigureTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable an extension.
        /// </summary>
        internal static string PHPExtensionItemEnableTask {
            get {
                return ResourceManager.GetString("PHPExtensionItemEnableTask", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PHPExtensions32 {
            get {
                object obj = ResourceManager.GetObject("PHPExtensions32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Extensions.
        /// </summary>
        internal static string PHPExtensionsItemTitle {
            get {
                return ResourceManager.GetString("PHPExtensionsItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable PHP extensions and configure PHP extensions settings..
        /// </summary>
        internal static string PHPExtensionsPageDescription {
            get {
                return ResourceManager.GetString("PHPExtensionsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string PHPExtensionsPageDisabledGroup {
            get {
                return ResourceManager.GetString("PHPExtensionsPageDisabledGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string PHPExtensionsPageDisableTask {
            get {
                return ResourceManager.GetString("PHPExtensionsPageDisableTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string PHPExtensionsPageEnabledGroup {
            get {
                return ResourceManager.GetString("PHPExtensionsPageEnabledGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string PHPExtensionsPageEnableTask {
            get {
                return ResourceManager.GetString("PHPExtensionsPageEnableTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting extensions.
        /// </summary>
        internal static string PHPExtensionsPageGettingExtensions {
            get {
                return ResourceManager.GetString("PHPExtensionsPageGettingExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP extensions provide additional functionality to PHP runtime, such as database connectivity, caching, debugging and others. Use this feature to enable or disable PHP extensions and to configure PHP extensions settings..
        /// </summary>
        internal static string PHPExtensionsPageLongDescription {
            get {
                return ResourceManager.GetString("PHPExtensionsPageLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PHPExtensionsPageNameField {
            get {
                return ResourceManager.GetString("PHPExtensionsPageNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string PHPExtensionsPageStateField {
            get {
                return ResourceManager.GetString("PHPExtensionsPageStateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Extensions.
        /// </summary>
        internal static string PHPExtensionsPageTitle {
            get {
                return ResourceManager.GetString("PHPExtensionsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the output of the phpinfo() function.
        /// </summary>
        internal static string PHPInfoPageDescription {
            get {
                return ResourceManager.GetString("PHPInfoPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the the output of phpinfo() function that provides the information about current state of PHP. This information can be used to examine all aspects of PHP runtime and for debugging purposes..
        /// </summary>
        internal static string PHPInfoPageLongDescription {
            get {
                return ResourceManager.GetString("PHPInfoPageLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phpinfo() output.
        /// </summary>
        internal static string PHPInfoPageTitle {
            get {
                return ResourceManager.GetString("PHPInfoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh phpinfo.
        /// </summary>
        internal static string PHPInfoRefreshPHPInfo {
            get {
                return ResourceManager.GetString("PHPInfoRefreshPHPInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this setting?.
        /// </summary>
        internal static string PHPIniSettingDeleteConfirmation {
            get {
                return ResourceManager.GetString("PHPIniSettingDeleteConfirmation", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PHPLogo16 {
            get {
                object obj = ResourceManager.GetObject("PHPLogo16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PHPLogo32 {
            get {
                object obj = ResourceManager.GetObject("PHPLogo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file:.
        /// </summary>
        internal static string PHPPageConfigurationFile {
            get {
                return ResourceManager.GetString("PHPPageConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP runtime configuration and settings.
        /// </summary>
        internal static string PHPPageDescription {
            get {
                return ResourceManager.GetString("PHPPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error log:.
        /// </summary>
        internal static string PHPPageErrorLog {
            get {
                return ResourceManager.GetString("PHPPageErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP executable:.
        /// </summary>
        internal static string PHPPageExecutable {
            get {
                return ResourceManager.GetString("PHPPageExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions path:.
        /// </summary>
        internal static string PHPPageExtensionsPath {
            get {
                return ResourceManager.GetString("PHPPageExtensionsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  | .
        /// </summary>
        internal static string PHPPageItemTaskSeparator {
            get {
                return ResourceManager.GetString("PHPPageItemTaskSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this feature to check the PHP runtime settings, to configure PHP runtime directives and to enable or disable PHP extensions..
        /// </summary>
        internal static string PHPPageLongDescription {
            get {
                return ResourceManager.GetString("PHPPageLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string PHPPageNone {
            get {
                return ResourceManager.GetString("PHPPageNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Manager.
        /// </summary>
        internal static string PHPPageTitle {
            get {
                return ResourceManager.GetString("PHPPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP version:.
        /// </summary>
        internal static string PHPPageVersion {
            get {
                return ResourceManager.GetString("PHPPageVersion", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PHPSettings32 {
            get {
                object obj = ResourceManager.GetObject("PHPSettings32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage all settings.
        /// </summary>
        internal static string PHPSettingsItemAllSettingsTask {
            get {
                return ResourceManager.GetString("PHPSettingsItemAllSettingsTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure error reporting.
        /// </summary>
        internal static string PHPSettingsItemErrorReportingTask {
            get {
                return ResourceManager.GetString("PHPSettingsItemErrorReportingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set runtime limits.
        /// </summary>
        internal static string PHPSettingsItemLimitsTask {
            get {
                return ResourceManager.GetString("PHPSettingsItemLimitsTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure PHP session.
        /// </summary>
        internal static string PHPSettingsItemSessionTask {
            get {
                return ResourceManager.GetString("PHPSettingsItemSessionTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Settings.
        /// </summary>
        internal static string PHPSettingsItemTitle {
            get {
                return ResourceManager.GetString("PHPSettingsItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        internal static string PHPSettingsPageAddSettingTask {
            get {
                return ResourceManager.GetString("PHPSettingsPageAddSettingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure all php settings.
        /// </summary>
        internal static string PHPSettingsPageDescription {
            get {
                return ResourceManager.GetString("PHPSettingsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit....
        /// </summary>
        internal static string PHPSettingsPageEditTask {
            get {
                return ResourceManager.GetString("PHPSettingsPageEditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting settings.
        /// </summary>
        internal static string PHPSettingsPageGettingSettings {
            get {
                return ResourceManager.GetString("PHPSettingsPageGettingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure all php settings that are stored in php.ini file. These setting control all aspects of PHP runtime, such error reporting, security, sessions and others..
        /// </summary>
        internal static string PHPSettingsPageLongDescription {
            get {
                return ResourceManager.GetString("PHPSettingsPageLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PHPSettingsPageNameField {
            get {
                return ResourceManager.GetString("PHPSettingsPageNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string PHPSettingsPageRemoveTask {
            get {
                return ResourceManager.GetString("PHPSettingsPageRemoveTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string PHPSettingsPageSectionField {
            get {
                return ResourceManager.GetString("PHPSettingsPageSectionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Settings.
        /// </summary>
        internal static string PHPSettingsPageTitle {
            get {
                return ResourceManager.GetString("PHPSettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string PHPSettingsPageValueField {
            get {
                return ResourceManager.GetString("PHPSettingsPageValueField", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PHPSetup32 {
            get {
                object obj = ResourceManager.GetObject("PHPSetup32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PHP version.
        /// </summary>
        internal static string PHPSetupItemChangeVersionTask {
            get {
                return ResourceManager.GetString("PHPSetupItemChangeVersionTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check phpinfo().
        /// </summary>
        internal static string PHPSetupItemCheckPHPInfoTask {
            get {
                return ResourceManager.GetString("PHPSetupItemCheckPHPInfoTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new PHP version.
        /// </summary>
        internal static string PHPSetupItemRegisterPHPTask {
            get {
                return ResourceManager.GetString("PHPSetupItemRegisterPHPTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Setup.
        /// </summary>
        internal static string PHPSetupItemTitle {
            get {
                return ResourceManager.GetString("PHPSetupItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify PHP setup.
        /// </summary>
        internal static string PHPSetupItemVerifyTask {
            get {
                return ResourceManager.GetString("PHPSetupItemVerifyTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new PHP version.
        /// </summary>
        internal static string RegisterPHPDialogRegisterNew {
            get {
                return ResourceManager.GetString("RegisterPHPDialogRegisterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder where PHP runtime binaries and PHP configuration file are located..
        /// </summary>
        internal static string RegisterPHPDialogSelectFolder {
            get {
                return ResourceManager.GetString("RegisterPHPDialogSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a &amp;domain name used for the selected site:.
        /// </summary>
        internal static string SelectSiteDomainDialogSelectADomain {
            get {
                return ResourceManager.GetString("SelectSiteDomainDialogSelectADomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a &amp;site where to check PHP configuration:.
        /// </summary>
        internal static string SelectSiteDomainDialogSelectASite {
            get {
                return ResourceManager.GetString("SelectSiteDomainDialogSelectASite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Site and Domain.
        /// </summary>
        internal static string SelectSiteDomainDialogTitle {
            get {
                return ResourceManager.GetString("SelectSiteDomainDialogTitle", resourceCulture);
            }
        }
    }
}
