//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Management.PHP.Powershell {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Management.PHP.Powershell.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string DeleteSettingWarningCaption {
            get {
                return ResourceManager.GetString("DeleteSettingWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting &quot;{0}&quot; and its value &quot;{1}&quot; will be removed from php.ini file. Are you sure you want to continue?.
        /// </summary>
        internal static string DeleteSettingWarningMessage {
            get {
                return ResourceManager.GetString("DeleteSettingWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension with name &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string ExtensionDoesNotExistError {
            get {
                return ResourceManager.GetString("ExtensionDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler with name &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string HandlerDoesNotExistError {
            get {
                return ResourceManager.GetString("HandlerDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Not set&gt;.
        /// </summary>
        internal static string NotSetValue {
            get {
                return ResourceManager.GetString("NotSetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP is not registered on this configuration level..
        /// </summary>
        internal static string PHPIsNotRegisteredError {
            get {
                return ResourceManager.GetString("PHPIsNotRegisteredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting with name &quot;{0}&quot; already exists. Use Set-PHPSetting cmdlet to change its value or Remove-PHPSetting to remove it..
        /// </summary>
        internal static string SettingAlreadyExistsError {
            get {
                return ResourceManager.GetString("SettingAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting with name &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string SettingDoesNotExistError {
            get {
                return ResourceManager.GetString("SettingDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PowerShell snapin for managing PHP installations on IIS 7..
        /// </summary>
        internal static string SnapInDescription {
            get {
                return ResourceManager.GetString("SnapInDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Manager Project.
        /// </summary>
        internal static string SnapInVendor {
            get {
                return ResourceManager.GetString("SnapInVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to view or modify IIS configuration. 
        ///Is PowerShell console launched in elevated mode (Run As Administrator)?.
        /// </summary>
        internal static string UserIsNotAdminError {
            get {
                return ResourceManager.GetString("UserIsNotAdminError", resourceCulture);
            }
        }
    }
}
